version: '2'

run:
  timeout: 10m
  tests: true

output: {}

linters:
  enable:
    - errcheck
    - goconst
    - gosec
    - govet
    - ineffassign
    - revive
    - unused
    - staticcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
